apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: node-app
  template:
    metadata:
      labels:
        app: node-app
    spec:
      containers:
      - name: node-app
        image: 279112112893.dkr.ecr.us-east-1.amazonaws.com/actions:fe8ca206f427b9a5d488c9d8d04aa44800543631
        ports:
        - containerPort: 3000
