apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: node-app
  template:
    metadata:
      labels:
        app: node-app
    spec:
      containers:
      - name: node-app
        image: 279112112893.dkr.ecr.us-east-1.amazonaws.com/actions:bd0d89da59ef65123eb1d5913793c08d4baf0728
        ports:
        - containerPort: 3000
